/* tests/web/r51_parlay.spec.mjs — R51 parlay pricing honesty on the card (project `web`).
 *
 * Proves, in the browser, that #/parlays renders and that every leg wears its
 * pricing honesty (app/views/parlays.js annotateLegs):
 *   - a SPREAD leg shows a NO EDGE chip whose tooltip is the feed's edge_note;
 *   - a PROP leg shows its provenance line — "calibrated on 2023-25" when the
 *     feed says pricing === "calibrated", "seed pricing" when it says "seed";
 *   - the legend copy states the spread verdict and the prop calibration.
 *
 * data/parlays.json is regenerated by the daily workflow only (network), so the
 * COMMITTED document may still be pre-R51 (no edge_note / pricing fields). Two
 * passes therefore:
 *   1. FIXTURE-DRIVEN: /data/parlays.json is routed to a copy of the committed
 *      document with R51 fields stamped on its legs, exactly as the builder now
 *      emits them — this is the assertion on the new markers.
 *   2. COMMITTED AS-IS: the chip still renders on spread legs (every spread leg
 *      is flat-priced by construction after R51, and the pre-R51 model the
 *      committed legs were priced by is the one measured to have no edge) and
 *      prop legs read "seed pricing" (the committed legs were seed-priced).
 */

import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';

const COMMITTED = JSON.parse(
  readFileSync(new URL('../../data/parlays.json', import.meta.url), 'utf8'),
);
const EDGE_NOTE = 'NO EDGE — cover model measured below coin-flip (log-loss 0.7231 vs '
  + '0.6931, 797 games 2023-25); priced flat until a margin model clears never-regress';
const PROPS = new Set(['qb_pass_yds', 'rb_rush_yds', 'wr_rec_yds']);

/** The committed document with the R51 leg fields the builder now emits. */
function r51Document() {
  const doc = JSON.parse(JSON.stringify(COMMITTED));
  let propSeen = 0;
  for (const p of doc.parlays) {
    for (const leg of p.legs) {
      if (leg.market === 'spread') {
        leg.model_prob = 0.5;
        leg.edge_note = EDGE_NOTE;
      } else if (PROPS.has(leg.market)) {
        propSeen += 1;
        leg.estimate = true;
        leg.line = leg.market === 'qb_pass_yds' ? 224.5 : 59.5;
        // Alternate so BOTH provenance lines are exercised.
        if (propSeen % 2 === 1) {
          leg.pricing = 'calibrated';
          leg.mu = 240.1; leg.sd = 76.66; leg.z = 0.2035;
        } else {
          leg.pricing = 'seed';
          leg.estimate_note = 'seed pricing — calibration file absent';
        }
      }
    }
  }
  return doc;
}

async function waitForCards(page) {
  await page.waitForSelector('.card.parlay', { timeout: 15000 });
}

test.describe('R51 — parlay leg pricing honesty on the card', () => {
  test('fixture-driven: NO EDGE chip on spread legs, provenance line on prop legs', async ({ page }) => {
    const doc = r51Document();
    const spreadLegs = doc.parlays.filter((p) => p.scope === 'game')
      .flatMap((p) => p.legs).filter((l) => l.market === 'spread').length;
    const propLegs = doc.parlays.filter((p) => p.scope === 'game')
      .flatMap((p) => p.legs).filter((l) => PROPS.has(l.market)).length;
    test.skip(spreadLegs === 0 || propLegs === 0,
      'committed parlays.json carries no spread or prop legs to annotate');

    await page.route('**/data/parlays.json', (route) => route.fulfill({
      status: 200, contentType: 'application/json', body: JSON.stringify(doc),
    }));
    await page.goto('/#/parlays');
    await waitForCards(page);

    // GAME scope is the default; every spread leg carries the chip + tooltip.
    const chips = page.locator('.card.parlay .leg .leg-noedge');
    await expect(chips).toHaveCount(spreadLegs);
    await expect(chips.first()).toHaveText('NO EDGE');
    await expect(chips.first()).toHaveAttribute('title', EDGE_NOTE);

    // Every prop leg carries a provenance line; both wordings appear.
    const prov = page.locator('.card.parlay .leg .leg-prov');
    await expect(prov).toHaveCount(propLegs);
    await expect(page.locator('.leg-prov[data-pricing="calibrated"]').first())
      .toHaveText('priced from this week’s projected yards, calibrated on 2023-25 — gate-verified');
    await expect(page.locator('.leg-prov[data-pricing="seed"]').first())
      .toContainText('seed pricing');

    // The annotations live INSIDE .leg: the card's leg count is untouched.
    const counts = await page.locator('.card.parlay').evaluateAll((cards) => cards.map((c) => [
      c.querySelectorAll('.legs > *').length, c.querySelectorAll('.legs > .leg').length,
    ]));
    for (const [all, legs] of counts) expect(all).toBe(legs);
  });

  test('committed document as-is: chip on spread legs, seed provenance on prop legs, honest legend', async ({ page }) => {
    await page.goto('/#/parlays');
    await waitForCards(page);
    const spreadLegs = COMMITTED.parlays.filter((p) => p.scope === 'game')
      .flatMap((p) => p.legs).filter((l) => l.market === 'spread').length;
    const propLegs = COMMITTED.parlays.filter((p) => p.scope === 'game')
      .flatMap((p) => p.legs).filter((l) => PROPS.has(l.market)).length;
    await expect(page.locator('.card.parlay .leg .leg-noedge')).toHaveCount(spreadLegs);
    await expect(page.locator('.card.parlay .leg .leg-prov')).toHaveCount(propLegs);
    if (propLegs > 0) {
      const anyCalibrated = COMMITTED.parlays.some((p) => p.legs.some((l) => l.pricing === 'calibrated'));
      if (!anyCalibrated) {
        await expect(page.locator('.leg-prov').first()).toContainText('seed pricing');
      }
    }
    const legend = page.locator('.legend');
    await expect(legend).toContainText('NO EDGE');
    await expect(legend).toContainText('calibrated on 2023-25');
  });
});
